import 'package:flutter/material.dart';
import 'package:get/get.dart';
import 'package:model_viewer_plus/model_viewer_plus.dart';
import '../model/product_model.dart';

class LandingPageController extends GetxController {
  FixedExtentScrollController listControllers=FixedExtentScrollController();
  List<Product> productList = [
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
    Product(
      id: 1,
      name: 'Nike Air Max 200',
      price: 240.00,
      isSelected: true,
      isliked: false,
      category: "Trending Now",
      imageList:['assets/egg_0.glb','assets/egg_1.glb','assets/egg_2.glb'],
      colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
    ),
    Product(
        id: 2,
        name: 'Nike Air Max 97',
        price: 220.00,
        isliked: false,
        imageList:['assets/egg_2.glb','assets/egg_1.glb','assets/egg_0.glb'],
        colorList:[const Color(0xff20262C),const Color(0xffffffff),const Color(0xff747F8F)],
        category: "Trending Now"),
  ];

  List<List<Widget>> listWheelScrollView=[];
  LandingPageController(){
    listWheelScrollViewWidget();
  }
  listWheelScrollViewWidget(){
    listWheelScrollView=[];
    for (var element in productList) {
      List<Widget> tempImage=element.imageList!.map((e) {
        return Container(
            height: 200,
            decoration: const BoxDecoration(
                shape: BoxShape.rectangle,
                color: Colors.transparent,
                borderRadius: BorderRadius.all(Radius.circular(20))
            ),
            child:ModelViewer(
              key: ValueKey('listWheelScrollViewWidget$e'),
              id: "oeuvreserer3D$e",
              autoRotateDelay: 500,
              backgroundColor: Colors.transparent,
              src:e,
              autoRotate: true,
              disableTap: true,
              disableZoom: true,
            )
        );
      }).toList();
      listWheelScrollView.add(tempImage);
    }
    update();
  }
}